version: '3'
services:
  nginx:
    image: "nginx:latest"
    ports:
     - "80:80"
    volumes:
     - ./static:/usr/share/nginx/html
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
  redis:
    image: "redis:alpine"


